spring:
  datasource:
    url: jdbc:mariadb://ec2-3-129-195-197.us-east-2.compute.amazonaws.com/KSY
    username: ksy
    password: ksy1010%%
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 157032577677-bm5dmdrgbtnk59f7qeccgc6hcat8g3pm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 62lICi3hpPGoXr91orAX
            client-secret: 2sm0vv5HAw
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/home

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /templates/




server:
  port: 8086
